"""add_scanned_image_url_to_submissions

Revision ID: 266181194c46
Revises: ee5b2cb7b5b3
Create Date: 2026-05-30 17:46:10.335599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266181194c46'
down_revision: Union[str, Sequence[str], None] = 'ee5b2cb7b5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('scanned_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'scanned_image_url')
    # ### end Alembic commands ###
