"""add_subscriptions_table

Revision ID: 2e22fa6c91d2
Revises: 9a13c6585514
Create Date: 2026-06-01 13:14:10.577713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e22fa6c91d2'
down_revision: Union[str, Sequence[str], None] = '9a13c6585514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', name='plantype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trial', name='subscriptionstatus'), nullable=False),
    sa.Column('papers_used', sa.Integer(), nullable=True),
    sa.Column('papers_limit', sa.Integer(), nullable=True),
    sa.Column('razorpay_sub_id', sa.String(), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
