"""add_exam_language

Revision ID: d255cfc99168
Revises: a6d59b2c86f0
Create Date: 2026-05-30 22:33:49.838952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd255cfc99168'
down_revision: Union[str, Sequence[str], None] = 'a6d59b2c86f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'language')
    # ### end Alembic commands ###
