"""add_raw_text_to_submissions

Revision ID: e4d8b0325704
Revises: 2e22fa6c91d2
Create Date: 2026-06-07 19:17:10.143605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d8b0325704'
down_revision: Union[str, Sequence[str], None] = '2e22fa6c91d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'raw_text')
    # ### end Alembic commands ###
