"""add_flagged_and_scored_at_to_answers

Revision ID: ee5b2cb7b5b3
Revises: 92039c5ff72f
Create Date: 2026-05-30 17:19:27.284925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5b2cb7b5b3'
down_revision: Union[str, Sequence[str], None] = '92039c5ff72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('flagged_for_review', sa.Boolean(), nullable=False))
    op.add_column('answers', sa.Column('scored_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'scored_at')
    op.drop_column('answers', 'flagged_for_review')
    # ### end Alembic commands ###
